# Generated by Django 5.0.6 on 2024-06-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_add_courses_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50)),
                ('e_email', models.CharField(max_length=50)),
                ('e_subject', models.CharField(max_length=100)),
                ('e_message', models.CharField(max_length=50)),
            ],
        ),
    ]
